Auth
Basic-Data-Infrastructure/association-registry pull request #1
Opened 2024-07-16 16:18 UTC by joodie

2024-07-29 10:11 UTC, remvee requested changes

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication.clj
> +                           (assoc cache :latest-new? false)
`has?` will not evict expired entries (see also [cache.clj](https://github.com/clojure/core.cache/blob/99fbd669a429bc800ff32b64b21cf82b6b486f06/src/main/clojure/clojure/core/cache.clj#L278)) so you'll need to do that yourself:

```clojure
(if (cache/has? impl jti)
  (-> cache
      (update :impl cache/evict jti)
      (assoc cache :latest-new? false))
  (-> cache
      (update :impl cache/miss jti true)
      (assoc :latest-new? true)))
```

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication.clj
> +            (bad-request "sub != client_id")
`iss` test uitsplitsen tbv foutmelding

```clojure
(not= client_id sub)
(bad-request "client_id != sub")

(not= sub iss)
(bad-request "sub != iss")
```

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication.clj
> +          (bad-request (ex-message e))))))
Is dit niet een "internal server" error?

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication.clj
> +            (let [party (data-source/party data-source sub)]
Is het hier niet duidelijker om `client_id` ipv `sub` te gebruiken?

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication.clj
> +                (let [token (access-token/mk-access-token {:client-id                (get party "party_id")
Waarom niet `client_id` ipv `(get party "party_id")`, kan dat iets anders zijn?  Zoja, hoe dan?

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication/access_token.clj
> +                :client-id (access-token->client-id access-token opts)))
`access-token->client-id` kan een exception gooien, moet deze niet afgevangen worden en een `401 Unauthorized` of iets dergelijks opleveren?

2024-07-29 10:11 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication/x5c.clj
> +    (when (signing-certificate? (first certs))
Moet deze vraag niet over alle certificaten gesteld worden?  En als er een cert tussen zit dat geen signing cert is, hebben we dan een "false" of een echt "error"?  Het lijkt mij, maar misschien is dat te streng, dat er dan exceptions gegooid en gelogd moeten worden.

2024-07-29 10:11 UTC, remvee commented on test/org/bdinetwork/assocation_register/authentication_test.clj
> +  (doseq [[res req] [[{:status 405}
`status/method-not-allowed`

2024-07-29 10:11 UTC, remvee commented on test/org/bdinetwork/assocation_register/authentication_test.clj
> +      (is (= client-id (:client-id (:req res)))))))
Ik had niet nog meer tests verwacht zoals verkeerde `sub`, `iss`, stale `jti`, expired token, etc.

2024-07-29 10:11 UTC, remvee commented on test/test-config.template.yml
> +      end_date: '2025-02-13T00:00:00.000Z'
Kunnen deze eindtijden iets optimistischer?  Bijv. `2100-01-01T00:00:00.000Z`.

2024-07-29 10:11 UTC, remvee commented on test/test-config.template.yml
> +    - expiry_date: '2025-02-13T00:00:00.000Z'
idem.

2024-07-29 10:11 UTC, remvee commented on test/test-config.template.yml
> +    - expiry_date: '2025-02-13T00:00:00.000Z'
Idem.

2024-07-29 10:11 UTC, remvee commented on test/test-config.template.yml
> +      end_date: '2025-02-12T00:00:00.000Z'
Idem.

2024-08-27 12:28 UTC, joodie commented on src/org/bdinetwork/assocation_register/authentication.clj
> +                           (assoc cache :latest-new? false)
That is silly. If the cache has? the item, it's by definition not expired. See the code you linked.

If I add the code you suggested, all entries are evicted after the first attempt at retrieving them.

2024-10-08 09:51 UTC, remvee requested changes

2024-10-08 09:51 UTC, remvee commented on Dockerfile
> +RUN apt-get install -y curl
why do we need curl?

2024-10-08 09:51 UTC, remvee commented on dev/logback.xml
> +  <root level="debug">
Maybe have a default level of "info" and a logger level "debug" on "org.bdinetwork" instead?

2024-10-08 09:51 UTC, remvee commented on src/org/bdinetwork/association_register/main.clj
> +    (wait-until-interrupted)))
Okay, I get it.. `nl.jomco.resources` does not allow us to have jetty "join".  So many this `.addShutdownHook` and `wait-until-interrupted` should go into `nl.jomco.resources` by adding the option to "join" to `system/run-system` for instance?

2024-10-08 09:51 UTC, remvee commented on src/org/bdinetwork/association_register/system.clj
> +              jetty (run-jetty handler {:join? false :port (:port config) :hostname (:hostname config)})]
Comma's for readability.

2024-10-08 09:51 UTC, remvee commented on src/org/bdinetwork/association_register/web.clj
> +                                                                     :sub server-id ;; TODO: check this
"check" what?

2024-10-08 09:51 UTC, remvee commented on src/org/bdinetwork/association_register/web.clj
> +           (log/info (str (:status response) " " (:request-method request) " " (:uri request)))
Jetty is already logging this, right?

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/system_test.clj
> +  {:ishare/satellite-endpoint "http://localhost:8080"
Extract port number to a var and make it overridable via environment var.

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/system_test.clj
> +   :port                     8080
So above.

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/system_test.clj
> +      ;; what should be the format when no party exists?
Maybe we should start making tickets in the issue tracker of this repo for this?  Also for https://github.com/Basic-Data-Infrastructure/association-registry/pull/1/files#diff-3b8baf2bfe76f9188d9fd0c37d9131b09e8a350a500c675cc8442f5763ad10f4R45

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/web_test.clj
> +   :port                     8080
Same as https://github.com/Basic-Data-Infrastructure/association-registry/pull/1/files#diff-9561188276803a63e8b3e245b790bf230afe58155084af401514b66a2a27e6abR16 please extract into a test-helper.

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/web_test.clj
> +    (is (= 200 (:status resp)))
`http-status/ok`

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/system_test.clj
> +      (is (= 200 status))
`http-status/ok`

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/system_test.clj
> +      (is (= 200 status))
`http-status/ok`

2024-10-08 09:51 UTC, remvee commented on test/org/bdinetwork/association_register/web_test.clj
> +            [nl.jomco.http-status-codes :as status]))
`http-status` is a clearer alias

2024-10-08 09:51 UTC, remvee commented on src/org/bdinetwork/association_register/web.clj
> +            [nl.jomco.http-status-codes :as status]
`http-status` is a clearer alias.

2024-10-15 09:26 UTC, remvee commented on src/org/bdinetwork/assocation_register/authentication.clj
> +                           (assoc cache :latest-new? false)
Okay, the suggested code is wrong but to me it seems the entry is never evicted and will remain in the cache for ever.

2024-10-17 09:25 UTC, remvee approved these changes

2024-10-17 09:29 UTC, merged